<?php

function documentlist_menu($may_cache) {
$items = array();
 if ($may_cache) {
   $items[] = array(
     'path' => 'generalassembly',
     'title' => t('General Assembly'),	
     'callback' => 'generalassembly_page',
     'access' => user_access('access content'),   
    );
  $items[] = array(
    'path' => 'securitycouncil',
    'title' => t('Security Council'),	
    'callback' => 'securitycouncil_page',
    'access' => user_access('access content'),   
   );
 }
 return $items;
}


function generalassembly_page() {
	$session_years = session_years();
  if (!$session_years['sessions'][arg(1)]) {  
    return document_table("ga");
  } else {
	  return theme('agenda_list',arg(1));
  }
}

function securitycouncil_page() {
	$session_years = session_years();	
  if (!isset($session_years['years'][arg(1)])) {  
    return document_table("sc");
  } else {
    return theme('sc_list',arg(1));
  }
}

function ga_session($year) {
  $session = arg(1);
  $nyear = $year+1;
  $output[] = "Session ".$session." (September ".$year." to September ". $nyear .")";
  $search = implode('<br />',theme('titles',xapian_do_search("session:ga$session class:heading",0,100)));
//  print_r($search);
$output[] = $search;
  return implode("\n",$output);
}

function document_date_browse() {
	$date['year'] = arg(3);
  if(arg(4)) $date['month'] = arg(4);
  if(arg(5)) $date['day'] = arg(5);
	$datestr = implode('-',$date);
  $search = xapian_do_search('date:'.$datestr);
  $output = theme('titles',$search);
	return implode('',$output);
}

function document_table($body = null) {
	$session_years = session_years();	
  if ($body == "ga") {
	  $title = "Session";
	} elseif ($body == "sc") {
		$title = "Year";
	} else {
		$title = "Year/Session";
	}
  $years = array_reverse($session_years['years'], true);
  $header = array($title,"Verbatim");
  foreach ($years as $year => $session) {
    $nyear = $year + 1;
	  if ($body == "sc") {
		  $rows[] = array(
			  $year,
			  l('Documents','securitycouncil/'.$year),
//			  l('PDFS','documents/pdf/year/'.$year['year'])
			);
		}
	  if ($body == "ga") {
		  $rows[] = array(
			  $session . " ($year/$nyear)",
			  l('Agenda','generalassembly/'.$session),
//			  l('PDFS','documents/pdf/session/'.$session)
			);
	  }		
	  if (!$body) {
			  $rows[] = array(
				  $year,
				  l('Documents','documents/verbatim/year/'.$year),
//				  l('PDFS','documents/pdf/year/'.$year['year'])
				);

		  $rows[] = array(
			  $session,
			  l('Agenda','documents/session/'.$session),
//			  l('PDFS','documents/pdf/session/'.$session)
			);


	  }		
	
  }
  return theme('table',$header,$rows);
}

function session_years() {
	$year = "1994";
	$session = "49";
	$i = 0;
	$thisyear = date(m) >= 9 ? date(Y) : date(Y)-1;
	while($year <= $thisyear) {
		$info['years'][$year]  = $session;
		$info['sessions'][$session] = $year;
		$year++;
		$session++;
		$i++;
	}
  return $info;
}
