#!/bin/bash

if [ "$1" == "0" ]
then
    echo "FAI error check: total successs!"
else
    echo "FAI error check: some failure"
fi

# Tell TheyWorkForYou to update
PRODSCRIPT=ukparse-morning-update-done.cgi
snarf -q http://cake.ukcod.org.uk/~fawkes/$PRODSCRIPT - > /dev/null &

# Update division archive for Public Whip to feed from
./divisionextractor.pl

# tell Public Whip to update
PRODSCRIPT=ukparse-morning-update-done.cgi
snarf -q http://www.publicwhip.org.uk/$PRODSCRIPT - > /dev/null &
