#!/bin/bash

# Tell TheyWorkForYou to update
PRODSCRIPT=ukparse-morning-update-done.cgi
snarf -q http://cake.ukcod.org.uk/~fawkes/$PRODSCRIPT - > /dev/null &

# Update division archive for Public Whip to feed from
./divisionextractor.pl

# tell Public Whip to update
PRODSCRIPT=ukparse-morning-update-done.cgi
snarf -q http://www.publicwhip.org.uk/$PRODSCRIPT - > /dev/null &
