#!/bin/bash

# Commons update

FROMDATE=$1
TODATE=$2
# $3 is extra flags to pass through
# echo "updatedaterange from $1 to $2"

# Run XML-generating scraper from Public Whip, getting new files from network
# and parsing the written answers and debates.
cd ~/parlparse/pyscraper
# We do these on separate lines, so if one fails, others still run
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse debates
echo "FAI test error is $?"
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse wrans
echo "FAI test error is $?"
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse westminhall
echo "FAI test error is $?"
./lazyrunall.py $3 --quietc --from=$FROMDATE --to=$TODATE parse wms
echo "FAI test error is $?"

# Yeah, it's not as fully featured as the UK Parliament one. But it should work :)
cd ~/parlparse/pyscraper/ni
./parse.py

# Public Bill Committee transcripts
cd ~/parlparse/pyscraper/standing
./parse.py
