<?php


function memberstates_menu($may_cache) {

$items = array();
 if ($may_cache) {
   $items[] = array(
     'path' => 'members',
     'title' => t('Member States'),
     'callback' => 'member_states_page',
     'access' => user_access('access content'),   
    );
 }
 return $items;

  
}



function format_state($text) {
  print $text;
      $text = l($text, 'members/'.$text[1]);
  return $text;
}




function member_states_page() {
$states = member_states();
$statename = arg(1);
if ($states[$statename]) {
  $state = $states[$statename];
  drupal_set_title("Information about ". $statename);
  $output .= "<dl>";
  $output .= "<dt>Joined</dt>";
  $output .= "<dd>".$state['#joined']."</dd>";


  if ($state['#formally']) {
    $output .= "<dt>Formally</dt>";
    foreach ($state['#formally'] as $former) {
      $output .= "<dd>".$former."</dd>";
    }
  }
  
  if ($state['#notes']) {
    $output .= "<dt>Notes</dt>";
    foreach ($state['#notes'] as $note) {
      $output .= "<dd>".$note."</dd>";
    }
  }
  $output .= "</dl>";
  
  if ($state['#original']) {
  $output .=  $statename . " was an original UN member state";
  }
  return $output;
} else {
$output = "<ul>";
foreach ($states as $state => $info) {
  $output .= "<li>". l($state, "members/".$state) ."</li>";
}
$output .= "</ul>";
return $output;
}



}


function get_state_info() {


}



function member_states() {

$states["Afghanistan"] = array(
	'#name' => '',
	'#joined' => '19/11/46',
	); 	
$states["Albania"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Algeria"] = array(
	'#name' => '',
	'#joined' => '08/10/62',
	); 	
$states["Andorra"] = array(
	'#name' => '',
	'#joined' => '28/07/93',
	); 	
$states["Angola"] = array(
	'#name' => '',
	'#joined' => '01/12/76',
	); 	
$states["Antigua and Barbuda"] = array(
	'#name' => '',
	'#joined' => '11/11/81',
	); 	
$states["Argentina"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,
	); 	
$states["Armenia"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	);
$states["Australia"] = array(
	'#name' => '',
	'#joined' => '01/11/45',
	'#original' => true,
	); 	
$states["Austria"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Azerbaijan"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	);
$states["Bahamas"] = array(
	'#name' => '',
	'#joined' => '18/09/73',
	); 	
$states["Bahrain"] = array(
	'#name' => '',
	'#joined' => '21/09/71',
	); 	
$states["Bangladesh"] = array(
	'#name' => '',
	'#joined' => '17/09/74',
	); 	
$states["Barbados"] = array(
	'#name' => '',
	'#joined' => '09/12/66',
	); 	
$states["Belarus"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,
	'#formally' => array("Byelorussian Soviet Socialist Republic"),
	'#notes' => array('Belarus was originally admitted as the "Byelorussian Soviet Socialist Republic". It informed the UN that it had changed its name from "Byelorussia" to its current name on 19 September 1991.'),
	);
$states["Belgium"] = array(
	'#name' => '',
	'#original' => true,
	'#joined' => '27/12/45',
	); 	
$states["Belize"] = array(
	'#name' => '',
	'#joined' => '25/09/81',
	); 	
$states["Benin"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	'#notes' => array('Benin was originally admitted as "Dahomey".'),
	); 	
$states["Bhutan"] = array(
	'#name' => '',
	'#joined' => '21/09/71',
	); 	
$states["Bolivia"] = array(
	'#name' => '',
	'#joined' => '14/11/45',
	'#original' => true,
	); 	
$states["Bosnia and Herzegovina"] = array(
	'#name' => '',
	'#joined' => '22/05/92',
	);
$states["Botswana"] = array(
	'#name' => '',
	'#joined' => '17/10/66',
	); 	
$states["Brazil"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Brunei"] = array(
	'#name' => '',
	'#joined' => '21/09/84',
	'#notes' => array('Brunei currently takes its seat under the name "Brunei Darussalam".'),
	); 	
$states["Bulgaria"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Burkina Faso"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	'#notes' => array('Burkina Faso was originally admitted as "Upper Volta".'),
	); 	
$states["Burundi"] = array(
	'#name' => '',
	'#joined' => '18/09/62',
	); 	
$states["Cambodia"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Cameroon"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	'#notes' => array('Cameroon was originally admitted as "Cameroun".'),	
	); 	
$states["Canada"] = array(
	'#name' => '',
	'#joined' => '09/11/45',
	'#original' => true,		
	); 	
$states["Cape Verde"] = array(
	'#name' => '',
	'#joined' => '16/09/75',
	); 	
$states["Central African Republic"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["Chad"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["Chile"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["China"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	);
$states["Colombia"] = array(
	'#name' => '',
	'#joined' => '05/11/45',
	'#original' => true,	
	); 	
$states["Comoros"] = array(
	'#name' => '',
	'#joined' => '12/11/75',
	); 	
$states["Democratic Republic of the Congo"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	'#notes' => array("The Democratic Republic of the Congo was originally admitted as \"Congo (Leopoldville)\". It later changed its name to the \"Democratic Republic of the Congo\", and then to \"Zaire\", and back to its current name on 17 May 1997."),
	); 	
$states["Republic of the Congo"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	'#notes' => array('The Republic of the Congo currently takes its seat under the name "Congo". It was originally admitted as "Congo (Brazzaville)".'),
	); 	
$states["Costa Rica"] = array(
	'#name' => '',
	'#joined' => '02/11/45',
	'#original' => true,	
	); 	
$states["Côte d'Ivoire"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	'#notes' => array("Côte d'Ivoire was originally admitted as \"Ivory Coast\"."),
	); 	
$states["Croatia"] = array(
	'#name' => '',
	'#joined' => '22/05/92',
	);
$states["Cuba"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Cyprus"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["Czech Republic"] = array(
	'#name' => '',
	'#joined' => '19/01/93',
	);
$states["Denmark"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Djibouti"] = array(
	'#name' => '',
	'#joined' => '20/09/77',
	); 	
$states["Dominica"] = array(
	'#name' => '',
	'#joined' => '18/12/78',
	); 	
$states["Dominican Republic"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Ecuador"] = array(
	'#name' => '',
	'#joined' => '21/12/45',
	'#original' => true,	
	); 	
$states["Egypt"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	);
$states["El Salvador"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Equatorial Guinea"] = array(
	'#name' => '',
	'#joined' => '12/11/68',
	); 	
$states["Eritrea"] = array(
	'#name' => '',
	'#joined' => '28/05/93',
	); 	
$states["Estonia"] = array(
	'#name' => '',
	'#joined' => '17/09/91',
	);
$states["Ethiopia"] = array(
	'#name' => '',
	'#joined' => '13/11/45',
	'#original' => true,	
	); 	
$states["Fiji"] = array(
	'#name' => '',
	'#joined' => '13/10/70',
	); 	
$states["Finland"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["France"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Gabon"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["Gambia"] = array(
	'#name' => '',
	'#joined' => '21/09/65',
	); 	
$states["Georgia"] = array(
	'#name' => '',
	'#joined' => '31/07/92',
	);
$states["Germany"] = array(
	'#name' => '',
	'#joined' => '18/09/73',
	);
$states["Ghana"] = array(
	'#name' => '',
	'#joined' => '08/03/57',
	); 	
$states["Greece"] = array(
	'#name' => '',
	'#joined' => '25/10/45',
	'#original' => true,	
	); 	
$states["Grenada"] = array(
	'#name' => '',
	'#joined' => '17/09/74',
	); 	
$states["Guatemala"] = array(
	'#name' => '',
	'#joined' => '21/11/45',
	'#original' => true,	
	); 	
$states["Guinea"] = array(
	'#name' => '',
	'#joined' => '12/12/58',
	); 	
$states["Guinea-Bissau"] = array(
	'#name' => '',
	'#joined' => '17/09/74',
	); 	
$states["Guyana"] = array(
	'#name' => '',
	'#joined' => '20/09/66',
	); 	
$states["Haiti"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Honduras"] = array(
	'#name' => '',
	'#joined' => '17/12/45',
	'#original' => true,	
	); 	
$states["Hungary"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Iceland"] = array(
	'#name' => '',
	'#joined' => '19/11/46',
	); 	
$states["India"] = array(
	'#name' => '',
	'#joined' => '30/10/45',
	'#original' => true,	
	); 	
$states["Indonesia"] = array(
	'#name' => '',
	'#joined' => '28/09/50',
	'#notes' => array("Indonesia temporarily withdrew from the UN on 20 January 1965 in response to the fact that Malaysia was elected as a non-permanent member of the Security Council. It announced its intention to \"resume full cooperation with the United Nations and to resume participation in its activities\" on 19 September 1966, and was invited to re-join the UN on 28 September 1966."),
	); 	
$states["Iran"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	'#notes' => array("Iran currently takes its seat under the name \"Iran (Islamic Republic of)\"."),
	); 	
$states["Iraq"] = array(
	'#name' => '',
	'#joined' => '21/12/45',
	'#original' => true,	
	); 	
$states["Ireland"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Israel"] = array(
	'#name' => '',
	'#joined' => '11/05/49',
	); 	
$states["Italy"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Jamaica"] = array(
	'#name' => '',
	'#joined' => '18/09/62',
	); 	
$states["Japan"] = array(
	'#name' => '',
	'#joined' => '18/12/56',
	); 	
$states["Jordan"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Kazakhstan"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	);
$states["Kenya"] = array(
	'#name' => '',
	'#joined' => '16/12/63',
	); 	
$states["Kiribati"] = array(
	'#name' => '',
	'#joined' => '14/09/99',
	); 	
$states["Democratic Peoples Republic of Korea"] = array(
	'#name' => '',
	'#joined' => '17/09/91',
	); 	
$states["South Korea"] = array(
	'#name' => '',
	'#joined' => '17/09/91',
	); 	
$states["Kuwait"] = array(
	'#name' => '',
	'#joined' => '14/05/63',
	); 	
$states["Kyrgyzstan"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	);
$states["Laos"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	'#notes' => array("Laos currently takes its seat under the name \"Lao People's Democratic Republic\"."),
	); 	
$states["Latvia"] = array(
	'#name' => '',
	'#joined' => '17/09/91',
	);
$states["Lebanon"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Lesotho"] = array(
	'#name' => '',
	'#joined' => '17/10/66',
	); 	
$states["Liberia"] = array(
	'#name' => '',
	'#joined' => '02/11/45',
	'#original' => true,	
	); 	
$states["Libya"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	'#notes' => array("Libya currently takes its seat under the name \"Libyan Arab Jamahiriya\".")
	); 	
$states["Liechtenstein"] = array(
	'#name' => '',
	'#joined' => '18/09/90',
	); 	
$states["Lithuania"] = array(
	'#name' => '',
	'#joined' => '17/09/91',
	);
$states["Luxembourg"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Republic of Macedonia"] = array(
	'#name' => '',
	'#joined' => '08/04/93',
	'#notes' => array("Macedonia currently takes its seat under the name \"The former Yugoslav Republic of Macedonia\", ". l('due to objections from Greece','http://en.wikipedia.org/wiki/Macedonia_naming_dispute')),
	);
$states["Madagascar"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["Malawi"] = array(
	'#name' => '',
	'#joined' => '01/12/64',
	); 	
$states["Malaysia"] = array(
	'#name' => '',
	'#joined' => '17/09/57',
	'#notes' => array("Malaysia was originally admitted as the \"Federation of Malaya\". On 16 September 1963, its name was changed to \"Malaysia\", following the admission of Singapore, Sabah and Sarawak to the federation. Singapore became an independent state on 9 August 1965."),
	); 	
$states["Maldives"] = array(
	'#name' => '',
	'#joined' => '21/09/65',
	); 	
$states["Mali"] = array(
	'#name' => '',
	'#joined' => '28/09/60',
	); 	
$states["Malta"] = array(
	'#name' => '',
	'#joined' => '01/12/64',
	); 	
$states["Marshall Islands"] = array(
	'#name' => '',
	'#joined' => '17/09/91',
	); 	
$states["Mauritania"] = array(
	'#name' => '',
	'#joined' => '27/10/61',
	); 	
$states["Mauritius"] = array(
	'#name' => '',
	'#joined' => '24/04/68',
	); 	
$states["Mexico"] = array(
	'#name' => '',
	'#joined' => '07/11/45',
	'#original' => true,	
	); 	
$states["Micronesia"] = array(
	'#name' => '',
	'#joined' => '17/09/91',
	'#notes' => array("Micronesia currently takes its seat under the name \"Micronesia (Federated States of)\"."),
	); 	
$states["Moldova"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	'#notes' => array("Moldova currently takes its seat under the name \"Republic of Moldova\"."),
	);
$states["Monaco"] = array(
	'#name' => '',
	'#joined' => '28/05/93',
	); 	
$states["Mongolia"] = array(
	'#name' => '',
	'#joined' => '27/10/61',
	); 	
$states["Montenegro"] = array(
	'#name' => '',
	'#joined' => '28/06/06',
	);
$states["Morocco"] = array(
	'#name' => '',
	'#joined' => '12/11/56',
	); 	
$states["Mozambique"] = array(
	'#name' => '',
	'#joined' => '16/09/75',
	); 	
$states["Myanmar"] = array(
	'#name' => '',
	'#joined' => '19/04/48',
	'#notes' => array("Myanmar was originally admitted as \"Burma\"."),
	); 	
$states["Namibia"] = array(
	'#name' => '',
	'#joined' => '23/04/90',
	); 	
$states["Nauru"] = array(
	'#name' => '',
	'#joined' => '14/09/99',
	); 	
$states["Nepal"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Netherlands"] = array(
	'#name' => '',
	'#joined' => '10/12/45',
	'#original' => true,	
	); 	
$states["New Zealand"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Nicaragua"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Niger"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["Nigeria"] = array(
	'#name' => '',
	'#joined' => '07/10/60',
	); 	
$states["Norway"] = array(
	'#name' => '',
	'#joined' => '27/11/45',
	'#original' => true,	
	); 	
$states["Oman"] = array(
	'#name' => '',
	'#joined' => '07/10/71',
	); 	
$states["Pakistan"] = array(
	'#name' => '',
	'#joined' => '30/09/47',
	); 	
$states["Palau"] = array(
	'#name' => '',
	'#joined' => '15/12/94',
	); 	
$states["Panama"] = array(
	'#name' => '',
	'#joined' => '13/11/45',
	'#original' => true,	
	); 	
$states["Papua New Guinea"] = array(
	'#name' => '',
	'#joined' => '10/10/75',
	); 	
$states["Paraguay"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Peru"] = array(
	'#name' => '',
	'#joined' => '31/10/45',
	'#original' => true,	
	); 	
$states["Philippines"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	'#notes' => array("The Philippines was originally admitted as the \"Philippine Commonwealth\"."),
	); 	
$states["Poland"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Portugal"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Qatar"] = array(
	'#name' => '',
	'#joined' => '21/09/71',
	); 	
$states["Romania"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Russia"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	'#notes' => array("Russia currently takes its seat under the name \"Russian Federation\"."),
	);
$states["Rwanda"] = array(
	'#name' => '',
	'#joined' => '18/09/62',
	); 	
$states["Saint Kitts and Nevis"] = array(
	'#name' => '',
	'#joined' => '23/09/83',
	); 	
$states["Saint Lucia"] = array(
	'#name' => '',
	'#joined' => '18/09/79',
	); 	
$states["Saint Vincent and the Grenadines"] = array(
	'#name' => '',
	'#joined' => '16/09/80',
	); 	
$states["Samoa"] = array(
	'#name' => '',
	'#joined' => '15/12/76',
	'#notes' => array("Samoa was originally admitted as \"Western Samoa\"."),
	); 	
$states["San Marino"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	); 	
$states["São Tomé and Príncipe"] = array(
	'#name' => '',
	'#joined' => '16/09/75',
	); 	
$states["Saudi Arabia"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Senegal"] = array(
	'#name' => '',
	'#joined' => '28/09/60',
	); 	
$states["Serbia"] = array(
	'#name' => '',
	'#joined' => '01/11/00',
	);
$states["Seychelles"] = array(
	'#name' => '',
	'#joined' => '21/09/76',
	); 	
$states["Sierra Leone"] = array(
	'#name' => '',
	'#joined' => '27/09/61',
	); 	
$states["Singapore"] = array(
	'#name' => '',
	'#joined' => '21/09/65',
	); 	
$states["Slovakia"] = array(
	'#name' => '',
	'#joined' => '19/01/93',
	);
$states["Slovenia"] = array(
	'#name' => '',
	'#joined' => '22/05/92',
	);
$states["Solomon Islands"] = array(
	'#name' => '',
	'#joined' => '19/09/78',
	); 	
$states["Somalia"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["South Africa"] = array(
	'#name' => '',
	'#joined' => '07/11/45',
	'#original' => true,	
	'#notes' => array("South Africa was originally admitted as the \"Union of South Africa\"."),
	); 	
$states["Spain"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	); 	
$states["Sri Lanka"] = array(
	'#name' => '',
	'#joined' => '14/12/55',
	'#notes' => array("Sri Lanka was originally admitted as \"Ceylon\"."),
	); 	
$states["Sudan"] = array(
	'#name' => '',
	'#joined' => '12/11/56',
	); 	
$states["Suriname"] = array(
	'#name' => '',
	'#joined' => '04/12/75',
	); 	
$states["Swaziland"] = array(
	'#name' => '',
	'#joined' => '24/09/68',
	); 	
$states["Sweden"] = array(
	'#name' => '',
	'#joined' => '19/11/46',
	); 	
$states["Switzerland"] = array(
	'#name' => '',
	'#joined' => '10/09/02',
	); 	
$states["Syria"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	'#notes' => array("Syria currently takes its seat under the name \"Syrian Arab Republic\"."),
	);
$states["Tajikistan"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	);
$states["Tanzania"] = array(
	'#name' => '',
	'#joined' => '14/12/61',
	'#notes' => array("Tanzania currently takes its seat under the name \"United Republic of Tanzania\"."),
	);
$states["Thailand"] = array(
	'#name' => '',
	'#joined' => '16/12/46',
	'#notes' => array("Thailand was originally admitted as \"Siam\"."),
	); 	
$states["Timor-Leste"] = array(
	'#name' => '',
	'#joined' => '27/09/02',
	); 	
$states["Togo"] = array(
	'#name' => '',
	'#joined' => '20/09/60',
	); 	
$states["Tonga"] = array(
	'#name' => '',
	'#joined' => '14/09/99',
	); 	
$states["Trinidad and Tobago"] = array(
	'#name' => '',
	'#joined' => '18/09/62',
	); 	
$states["Tunisia"] = array(
	'#name' => '',
	'#joined' => '12/11/56',
	); 	
$states["Turkey"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	); 	
$states["Turkmenistan"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	);
$states["Tuvalu"] = array(
	'#name' => '',
	'#joined' => '05/09/00',
	); 	
$states["Uganda"] = array(
	'#name' => '',
	'#joined' => '25/10/62',
	); 	
$states["Ukraine"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	'#notes' => array("Ukraine was originally admitted as the \"Ukrainian Soviet Socialist Republic\"."),
	);
$states["United Arab Emirates"] = array(
	'#name' => '',
	'#joined' => '09/12/71',
	); 	
$states["United Kingdom"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	'#notes' => array("The United Kingdom currently takes its seat under the name the \"United Kingdom of Great Britain and Northern Ireland\"."),
	); 	
$states["United States"] = array(
	'#name' => '',
	'#joined' => '24/10/45',
	'#original' => true,	
	'#notes' => array("The United States currently takes its seat under the name the \"United States of America\"."),
	); 	
$states["Uruguay"] = array(
	'#name' => '',
	'#joined' => '18/12/45',
	'#original' => true,	
	); 	
$states["Uzbekistan"] = array(
	'#name' => '',
	'#joined' => '02/03/92',
	);
$states["Vanuatu"] = array(
	'#name' => '',
	'#joined' => '15/09/81',
	); 	
$states["Venezuela"] = array(
	'#name' => '',
	'#joined' => '15/11/45',
	'#original' => true,	
	'#notes' => array("Venezuela currently takes its seat under the name the \"Venezuela (Bolivarian Republic of)\"."),
	); 	
$states["Vietnam"] = array(
	'#name' => '',
	'#joined' => '20/09/77',
	'#notes' => array("Vietnam currently takes its seat under the name \"Viet Nam\"."),
	); 	
$states["Yemen"] = array(
	'#name' => '',
	'#joined' => '30/09/47',
	);
$states["Zambia"] = array(
	'#name' => '',
	'#joined' => '01/12/64',
	); 	
$states["Zimbabwe"] = array(
	'#name' => '',
	'#joined' => '25/08/80',
	); 	
return $states;	
}