#!/bin/bash

# Run every morning

cd ~/unparse-live/scraper

python2.4 ./unmain.py --quiet --scrape-links --continue-on-error scrape cxml parse xapdex docmeasurements agendanames scsummaries nationdata

