<?php


function shistogram_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'shistogram',
      'title' => t('shistogram'),
      'access' => user_access('access content'),
      'callback' => 'shistogram_page'
     );
  }
  return $items;
}

function shistogram_page() {  
  
  // collect all the hits on this
  $xapsearchstring = arg(1); 
  
  $bbyheading = (preg_match('/class:heading/', $xapsearchstring) != 0); 
  
  $result = xapian_get_mset($xapsearchstring);
  $query = $result->query; 
  $enquire = $result->enquire; 
  $matches = $enquire->get_mset(0, 1999, 1999); 
  
  $Csecco = array();
  $Ctotal = array();
  $mseti = $matches->begin();
  while (! $mseti->equals($matches->end())) {
    $doc = $mseti->get_document();
    $doc_data = $doc->get_data();
    $doc_value = $doc->get_value(0);
    $doc_year = intval(substr($doc_value, 0, 4));
    $doc_body = substr($doc_value, 8, 3);
    
    $increm = 1; 
    if (! $bbyheading) {
      $ddoc_data = explode('|', $doc_data); 
      $increm = intval($ddoc_data[2]);
    }
    
    if ($doc_body == "SPV")
      $Csecco[$doc_year] += $increm;
    $Ctotal[$doc_year] += $increm;
    $mseti->next();
  }

  $maxhits = 10;
  $minyear = 1994;  // min(array_keys($Ctotal));
  $maxyear = 2007;
  foreach ($Ctotal as $year => $yhits)
    $maxhits = max($maxhits, $yhits);
  $maxhits += 10;

  $cwidth = 30; // pixels wide for each bar
  $width = ($maxyear - $minyear + 2) * $cwidth;
  $height = 300;

  $im = imagecreate($width, $height);
  $white = imagecolorallocate($im, 250, 213, 204);

  for ($year = $minyear; $year <= $maxyear; $year += 1) {
    $xlo = ($year - $minyear) * $cwidth + $cwidth / 2 + 1;
    $xhi = ($year - $minyear + 1) * $cwidth + $cwidth / 2 - 1;
    $atop = $Ctotal[$year] * ($height - 3) / $maxhits;
    $stop = $Csecco[$year] * ($height - 3) / $maxhits;
    $icol = imagecolorallocate($im, 0, 90, 200);
    ImageFilledRectangle($im, $xlo, $height - $atop, $xhi, $height - 1, $icol);
    if ($stop != 0) {
      $icol = imagecolorallocate($im, 190, 30, 120);
      ImageFilledRectangle($im, $xlo, $height - $stop, $xhi, $height - 1, $icol);
    }
    $icol = imagecolorallocate($im, 0, 200, 0); 
    //imagestring($im, 3, $xlo, 15, "$year", $icol); 
  }

  // write a message to help us
  $icol = imagecolorallocate($im, 50, 200, 20);
  //if (! $byheading){
  //   imagestring($im, 3, 10, 5, arg(1)." : ".$maxhits." ".$ddoc_data[2], $icol);
  //}  
  
  if ($message){
  //  imagestring($im, 5, 50, 50, $message, $icol); 
  }

  header('Content-type: image/png');

  print	imagepng($im);
  imagedestroy($im);

}




