<?php
/**
 * views template to output a view.
 * This code was generated by the views theming wizard
 * Date: Sat, 2006-11-11 17:24
 * View: meetings
 *
 * This function goes in your template.php file
 */
function phptemplate_views_view_list_meetings($view, $nodes, $type) {
  $fields = _views_get_fields();

  $taken = array();

  // Set up the fields in nicely named chunks.
  foreach ($view->field as $id => $field) {
    $field_name = $field['field'];
    if (isset($taken[$field_name])) {
      $field_name = $field['queryname'];
    }
    $taken[$field_name] = true;
    $field_names[$id] = $field_name;
  }

  // Set up some variables that won't change.
  $base_vars = array(
    'view' => $view,
    'view_type' => $type,
  );

  foreach ($nodes as $i => $node) {
    $vars = $base_vars;
    $vars['node'] = $node;
    $vars['count'] = $i;
    $vars['stripe'] = $i % 2 ? 'even' : 'odd';
    foreach ($view->field as $id => $field) {
      $name = $field_names[$id];
      $vars[$name] = views_theme_field('views_handle_field', $field['queryname'], $fields, $field, $node, $view);
      if (isset($field['label'])) {
        $vars[$name . '_label'] = $field['label'];
      }
    }
    $items[] = _phptemplate_callback('views-list-meetings', $vars);
  }
  if ($items) {
    return theme('view_list', $items);
  }
}

function theme_view_list($items = array(), $title = NULL, $type = 'ul') {
  $output = '<div class="view-list">';
  if (isset($title)) {
    $output .= '<h3>'. $title .'</h3>';
  }

  if (!empty($items)) {
    foreach ($items as $item) {
      $output .= $item;
    }
  }
  $output .= '</div>';
  return $output;
} 
