<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: 
 * View: meetings
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   meetings, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating.
 * $field_speaker_value -- 
 * $field_speaker_value_label -- The assigned label for $field_speaker_value
 * $field_nation_value -- 
 * $field_nation_value_label -- The assigned label for $field_nation_value
 * $field_text_value -- 
 * $field_text_value_label -- The assigned label for $field_text_value
 *
 * This function goes in your views-list-meetings.tpl.php file
 */
?>
<div class="stripe-<?php print $stripe . " " . $node->node_type?>">

<div class="speeker-info">

<?php if ($field_speaker_value) { ?>
<div class="speaker-info">
<dl>
<dt><?php print $field_speaker_value_label ?></dt>
<dd><?php print $field_speaker_value?></dd>
</dl>  
</div>
<?php } ?>



<?php if ($field_nation_value) { ?>
<div class="nation-info">
<dl>
<dt><?php print $field_nation_value_label ?></dt>
<dd><?php print $field_nation_value?></dd>
</dl>  
</div>
<?php } ?>

</div>

<div class="view-label view-field-field_text_value">
  <?php print $field_text_value_label ?>
</div>
<div class="view-field view-data-field_text_value">
  <?php print $field_text_value?>
</div>
</div>
